from typing import Any, Protocol


class DTOAssembler(Protocol):
    def to_dto(self, domain: Any) -> Any: ...

    def to_domain(self, dto: Any) -> Any: ...

    def to_dto_list(self, domain_list: list[Any]) -> list[Any]: ...

    def to_domain_list(self, dto_list: list[Any]) -> list[Any]: ...
