from typing import Any, Protocol


class EntityAssembler(Protocol):
    def to_entity(self, domain: Any) -> Any: ...

    def to_domain(self, entity: Any) -> Any: ...

    def to_entity_list(self, domain_list: list[Any]) -> list[Any]: ...

    def to_domain_list(self, entity_list: list[Any]) -> list[Any]: ...
